name:  Build and push on development
 
on:
  push:
    branches: [master]

env:
  DEPLOYMENT_PRD: kgmedia-prediction-algo

jobs:
  build-and-push:
    runs-on: [node20] 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
          
    - name: Login, Build & Push Image to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.DEPLOYMENT_PRD }}:${{ github.event.release.tag_name }} -f Dockerfile
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.DEPLOYMENT_PRD }}:${{ github.event.release.tag_name }}

  patch-to-aks-prd:
    runs-on: node20
    needs: build-and-push
    steps:    
    - name: REST API with curl
      run: |
        curl -I -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} "https://deploykid.kompaskita.com/job/kgmedia-app/job/kgmedia-prediction-algo/buildWithParameters?token=webhookremot&img_version=${{ github.event.release.tag_name }}"